language: node_js
node_js: 'node'
notifications:
  email: false
install:
  - export GK_LOCK_DEFAULT_BRANCH=saga
  - npm i -g greenkeeper-lockfile@2
  - npx greenkeeper-lockfile-update
  - npm ci --no-audit
before_script:
  - node -e 'const {version} = require("./package.json"); if(version !== "0.0.0-development") { console.error("\033[0;31mversion in package.json must be 0.0.0-development, but is " + version + "!\033[0m"); process.exit(1); }'
  - npm run lint
script:
  - npx tsc
after_success:
  - npx greenkeeper-lockfile-upload
    - npm i semantic-release; npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
